#install.packages('mlbench')
#install.packages('randomForest')
#install.packages('rpart.plot')
#install.packages('caret')
#install.packages('summarytools')
#install.packages('corrplot')
#remove.packages('party')
#remove.packages('e1071')
#remove.packages('pROC')
#remove.packages('tidyverse')
#remove.packages('ranger')
#remove.packages('tree')
```{r}
suppressMessages(library(mlbench))
suppressMessages(library(randomForest))
suppressMessages(library(rpart.plot))
suppressMessages(library(caret))
suppressMessages(library(summarytools))
suppressMessages(library(corrplot))

```
```{r}
data(PimaIndiansDiabetes)
data <- PimaIndiansDiabetes
head(data)
hist(data$insulin)
```
```{r}
set.seed(21)
data_partition <- createDataPartition(y = data$diabetes, p = 0.81, times = 1, list = FALSE)
train <- data[data_partition,]
test <- data[-data_partition,]
nrow(train)
```
```{r}
summary(data)
```
```{r}
descr(data)
```
```{r}
correlation <- cor(train[, setdiff(names(train), 'diabetes')])
corrplot(corr = correlation, col=c('yellow', 'green yellow', 'orange', 'pink', 'violet', 'purple'), method = 'pie')
```
```{r}
model_entropy<- rpart(formula = diabetes ~ ., data = train, method = 'class', minsplit=2, control = rpart.control(maxdepth = 5, minbucket = 1, cp=0.0), parms = list(split = 'information'))
rpart.plot(model_entropy)
model_entropy
```
```{r}
model_gini<- rpart(formula = diabetes ~ ., data = train, method = 'class', minsplit=2, control = rpart.control(maxdepth = 5, minbucket = 1, cp=0.0), parms = list(split = 'gini'))
rpart.plot(model_gini)
model_gini
```
```{r}
pred_entropy <- predict(model_entropy, test, type = 'class')
confusionMatrix(pred_entropy, test$diabetes, positive='pos')
```
```{r}
pred_gini <- predict(model_gini, test, type = 'class')
confusionMatrix(pred_gini, test$diabetes, positive='pos')
```
```{r}
model_rf <- randomForest(diabetes ~., data = train, maxnodes=23, ntree=8, mtry = sqrt(8), nodesize = 2)

pred_rpart <- predict(model_rf, test, type = 'class')
confusionMatrix(pred_rpart, test$diabetes, positive='pos')
model_rf
```

